# frontend/Dockerfile.prod
# Build stage
FROM node:18 as builder

WORKDIR /app

RUN npm install -g @quasar/cli

COPY package*.json ./
RUN npm install --ignore-scripts

COPY . .
RUN quasar build

# Production stage
FROM nginx:alpine

COPY --from=builder /app/dist/spa /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]