<template>
  <q-card class="bg-blue-2" bordered flat>
    <!-- Header Section - Now Clickable -->
    <q-card-section class="q-pa-md cursor-pointer" @click="toggleExpansion" v-ripple>
      <div class="row items-center no-wrap">
        <div class="col-auto">
          <q-icon name="warning" color="warning" size="md" class="q-mr-sm" />
        </div>
        <div class="col">
          <div class="text-subtitle1 text-weight-bold">Important Disclaimer</div>
        </div>
        <!-- Expansion Indicator Icon -->
        <div class="col-auto">
          <q-icon :name="isExpanded ? 'expand_less' : 'expand_more'" size="md" />
        </div>
      </div>
    </q-card-section>

    <!-- Collapsible Body Section -->
    <q-slide-transition>
      <div v-if="isExpanded">
        <q-separator />
        <q-card-section class="q-pt-sm text-body2">
          <p>
            This Heat Risk Calculator is provided for
            <strong>informational and entertainment purposes only</strong>.
          </p>
          <p>
            The results generated by this tool are estimations based on general data and
            <strong
              >should NOT be considered a substitute for professional medical advice, diagnosis, or
              treatment</strong
            >. It is not designed or intended to be used as a medical diagnostic tool.
          </p>
          <p>
            Always seek the advice of your physician or other qualified health provider with any
            questions you may have regarding a medical condition or heat-related concerns.
            <strong
              >Never disregard professional medical advice or delay in seeking it because of
              something you have read or calculated using this application.</strong
            >
          </p>
          <p>
            Reliance on any information provided by this calculator is solely at your own risk. The
            creators of this application assume no liability or responsibility for any consequences
            resulting directly or indirectly from any action or inaction you take based on the
            information found in or material linked to this tool.
          </p>
        </q-card-section>
      </div>
    </q-slide-transition>
  </q-card>
</template>

<script setup lang="ts">
import { ref } from 'vue'

// Reactive state to control the expansion
const isExpanded = ref(true) // Start expanded

// Function to toggle the expansion state
const toggleExpansion = () => {
  isExpanded.value = !isExpanded.value
}
</script>

<style scoped>
p {
  margin-bottom: 0.8em;
}
p:last-child {
  margin-bottom: 0;
}

/* Optional: Add a subtle transition for the icon rotation */
.q-icon {
  transition: transform 0.28s ease-out;
}
</style>
